# Step 1: Use a lightweight OpenJDK image as base
FROM openjdk:17-jdk-slim

# Step 2: Set a working directory inside the container
WORKDIR /app

# Step 3: Copy the jar file into the container
# Replace 'your-app-name.jar' with the actual jar file name generated by Maven/Gradle
COPY target/StudentManag.jar app.jar

# Step 4: Expose the application port (default: 8080)
EXPOSE 8080

# Step 5: Define the command to run your Spring Boot app
ENTRYPOINT ["java", "-jar", "app.jar"]
