spring.application.name=StudentManagement

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://host.docker.internal:5432/Demo}
#to make local psql to connect with docker container need to make it host.docker.internal
#and while mvn package(creating jar file) need to skip the unit test else it gives an error -> mvn clean package -DskipTests
#https://www.perplexity.ai/search/the-docker-is-not-runnig-its-s-xgX7044SQl2YZzMxcnQHtg#1
# For Render deployment, DATABASE_URL will be automatically provided by Render PostgreSQL service

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
